# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(default='', max_length=300)),
                ('subtitle', models.CharField(default='', max_length=300)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(max_length=300)),
                ('lede', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
