# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170703_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=300),
        ),
    ]
