# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170703_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(choices=[('liz', 'Elizabeth DiNunzio')], default='', max_length=300),
        ),
    ]
