# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(choices=[('liz', 'Elizabeth DiNunzio')], default='', max_length=300),
        ),
    ]
