# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170703_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(choices=[('Elizabeth DiNunzio', 'Elizabeth DiNunzio')], default='', max_length=300),
        ),
    ]
