# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170709_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=300)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
