# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
