# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='css',
            field=models.FileField(upload_to='css/'),
        ),
    ]
